"""
Django settings for digipay project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+w*0c^zo18m)i9+l#9b7ow#d)o7r%6*wacaq6n24*s9pwfj29n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['digipay-project.vercel.app','.now.sh','127.0.0.1','localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.humanize',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'transactions',
    'accounts',
    'bankaccounts',
    'crispy_forms',
    'crispy_bootstrap5',
    'captcha'
]

# Re-Captacha
RECAPTCHA_PUBLIC_KEY = '6Ld_h-YnAAAAAD2Wp7qQJL5tURFLeR3O2TOToQ_t'
RECAPTCHA_PRIVATE_KEY = '6Ld_h-YnAAAAAI85fwkxT0wzqKgNzTenfqZGK5i2'

# Crispy template packs
CRISPY_TEMPLATE_PACK = 'bootstrap5'
CRISPY_ALLOWED_TEMPLATE_PACK = 'bootstrap5'
# JAZZMIN SETTINGS CONFIGURATION
JAZZMIN_SETTINGS = {
    "site_brand": "DigiPay",
    "copyright": "DigiPay",
}

JAZZMIN_UI_TWEAKS = {
    
    "navbar_small_text" : True,
    "footer_small_text" : False,
    "body_small_text" : True,
    "brand__small_text" : False,
    "brand_color ": "navbar_indigo",
    "accent" : "accent-olive",
    "navbar" : "navbar-indigo",
    "accent" : "accent-olive",
    "navbar" : "navbar-indigo navbar-dark",
    "no_navbar_border" : True,
    "navbar_fixed" : False,
    "layout_boxed" : False,
    "footer_fixed" : False,
    "sidebar_fixed" : False,
    "sidebar" : "sidebar-dark-indigo",
    "sidebar_nav_small_text" : False,
    "sidebar_disable_expand" : False,
    "sidebar_nav_child_indent" : False,
    "sidebar_nav_compact_style" : False,
    "sidebar_nav_legacy_style" : False,
    "sidebar_nav_flat_style" : False,
    "theme" : "materia",
    "dark_mode_theme" : "slate",
    "button_classes" : {
        "primary" : "btn-primary",
        "secondary" : "btn-secondary",
        "info" : "btn-info",
        "warning" : "btn-warning",
        "danger" : "btn-danger",
        "success" : "btn-success"
    }
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digipay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates"),os.path.join(BASE_DIR, "templates/account"),os.path.join(BASE_DIR, "templates/partials")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'digipay.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'C3EDg6Dee5e5ac5D164Fd6afGbb2-Fef',
        'HOST': 'roundhouse.proxy.rlwy.net',
        'PORT': 14435
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'	

STATICFILES_DIRS = [
    
    os.path.join(BASE_DIR,"static")
]

STATIC_ROOT= os.path.join(BASE_DIR,'staticfiles_build','static')

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,"media/")



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
