# Generated by Django 4.2.4 on 2023-09-27 05:57

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0003_alter_account_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=25, prefix='DIGP', unique=True),
        ),
    ]
