# Generated by Django 4.2.4 on 2023-10-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0002_alter_account_id_alter_kyc_id'),
        ('bankaccounts', '0004_alter_account_account_id'),
    ]

    operations = [
    ]
