# Generated by Django 4.2.4 on 2023-10-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='Phone',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
