# Generated by Django 4.2.4 on 2023-08-22 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_user_profile_password_user_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='username',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='userimg/'),
        ),
    ]
