# Generated by Django 4.2.4 on 2023-10-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_user_profile_name_and_more'),
        ('accounts', '0005_remove_user_profile_user_and_more'),
    ]

    operations = [
    ]
