# Generated by Django 4.2.4 on 2023-09-20 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=15, max_length=25, prefix='', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('receiver', models.CharField(blank=True, max_length=200)),
                ('sender', models.CharField(blank=True, max_length=200)),
                ('receiver_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sender_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[['failed', 'FAILED'], ['completed', 'COMPLETED'], ['pending', 'PENDING'], ['processing', 'PROCESSING'], ['request_sent', 'REQUEST_SENT'], ['request_processing', 'REQUEST_PROCESSING']], default='pending', max_length=20)),
                ('transaction_type', models.CharField(choices=[['transfer', 'TRANSFER'], ['withdraw', 'WITHDRAW'], ['refund', 'REFUND'], ['received', 'RECEIVED'], ['request', 'REQUEST'], ['none', 'NONE']], default='none', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
