# Generated by Django 4.2.4 on 2023-09-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
