# Generated by Django 4.2.4 on 2023-09-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0002_kyc'),
        ('transactions', '0004_remove_transaction_receiver_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_account', to='bankaccounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_account', to='bankaccounts.account'),
        ),
    ]
