# Generated by Django 4.2.4 on 2023-10-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_creditcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='cvv',
            new_name='CVV',
        ),
    ]
