# Generated by Django 4.2.4 on 2023-10-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_rename_cvv_creditcard_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
