# Generated by Django 4.2.4 on 2023-10-28 05:18

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_creditcard_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='CVV',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=3, max_length=6, prefix='', unique=True),
        ),
    ]
