# Generated by Django 4.2.4 on 2023-10-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_receiver_account_and_more copy'),
        ('transactions', '0010_alter_creditcard_cvv'),
    ]

    operations = [
    ]
